### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by jihoonkim2100** [RoshanRane/toybrains#1]
## Documentation
- [x] create a doc folder to store all documentation-related files
- [x] ReadMe: add text introduction to the dataset
- [x] ReadMe: Add plots showing example images from the dataset and how they change for different values of each image generation attribute ($g_i \in G$). Currently we have 20 $g_i$. -> @RoshanRane 
- [x] ReadMe: Create an example causal DAG graph figure from [Diagrams.net](Diagrams.net) showing how different covariates (confounds) and labels can be made dependent on different $g_i$ in the toybrain images -> @RoshanRane  
- [x] viz notebook: Visualize the distribution of how the $g_i$ changes for different covariates and labels -> @RoshanRane 
> - [ ] Create 3D gifs of 3D latent space generated by applying PCA on the data:  -> @jihoonkim2100  

## Code
- [ ] Class `ToyBrainsData()` should **automatically create causal DAG graphs** figure showing how different labels $y_i \in Y$ affect the different GVs in the toybrain images and also interact with different covariates / confounds  $c_i \in C$ affect different GVs in the Toybrain images -> @RoshanRane
- [x] create a method that shows what the data gen probabilities are for all current covariate & labels
- [ ] Create brain_mask and shape_mask (binary) label images and save it the `toybrains/masks` folder label
- [x] Refactoring: Currently the code is complex to read: Refactor the code such that users can easily understand how to add new labels or change the relationships between labels and attributes and covariates and attributes
- [x] Allow multiple config files that can be passed as arg to `create_toybrains.py` -> @jihoonkim2100 

## Baselining
- [x] Create labels v1: 
    - purely based on the 5 shape attributes (combinations that are linear and non-linear)
    - partially based on confounder + partially shapes : see the idea from MDN
    - purely based on confounder pathway
- [x] Baselines evaluation: Fit baseline models on these labels and tweak the labels until they are not very easily predictable -> sub tasks https://github.com/RoshanRane/toybrains/issues/1#issuecomment-1574389739 -> @jihoonkim2100 
- [ ] Create labels v2
- [ ] Quantify how the change in generative distributions of the labels affect the Baseline model performances. 

## Testing
- [ ] check that all attribute distributions are working as expected
- [ ] unit testing (tbd)
- [ ] tutorial notebook (tbd)

**Comment by RoshanRane** [comment]
## Develop baseline models notebook
@jihoonkim2100 

#### **Baseline on attributes on logistic regression**: 
  - [x] Predict $A \mapsto y$ and $A \mapsto C$
  - [x] Predict $A + C \mapsto y$ 

#### Train on images **Supervised:** 
predict all labels, covariates and also generative parameters using different supervised deep learning methods and visualize them the learned representations on DeepRepViz
  - [ ] FCN
  - [ ] ResNet
  - [x] DenseNet
  - [ ] Supervised PCA
  - [ ] Linear FCN
  
#### **Unsupervised:** 
perform unsupervised latent representation extraction that are low-dimensional and visualize them on DeepRepViz and fit a simple ML model for accuracy
  - [x] PCA + Logistic regression on top
  - [ ] tSNE + Logistic regression on top
  - [x] MDS + Logistic regression on top
  - [ ] LDA + Logistic regression on top
  - [x] ICA + Logistic regression on top
  - [ ] Autoencoder latent rep + LR on top
  - [ ] VAE + LR on top
  
  #### Results visualisation (mid-result by 19th July)
  - [x] generate one toybrain dataset with a fixed seed for all 3 baseline notebooks
  - [x] Write the attribute-based baseline results, supervised image-based baseline and unsupervised image-based baselines results in one csv file.
  - [ ] Plot the results (accuracy with confidence intervals) for all these models side by side to compare.
